### PR TITLE
Add title version to CIA information.

### PR DESCRIPTION
**Pull request by ghost**
Reads the "[Ticket title version](https://www.3dbrew.org/wiki/Ticket#Ticket_Data)" field 10 bytes after the title ID. I'm not very familiar with your codebase, so if I missed a few necessary code additions, let me know.

### CODE REVIEW

**Comment by ksanislo** [comment]
@Steveice10 Last time I poked through here, that field was less reliable than scraping a version out of the filename or url. Have things improved since then? Locating and paring the TMD itself seemed to be the only realistic way to get a version that worked for most of the .cia files around.

I'll give it a try anyway though.

**Comment by ghost** [comment]
According to 3dbrew, it generally matches the TMD value. At the very least, anything made with makerom should have the correct value, as it assigns the same to both.

**Comment by ghost** [comment]
Any updates on the status of this PR?

**Comment by ghost** [comment]
@ksanislo Have you gotten around to trying this out?

**Comment by gaetschwartz** [comment]
@ksanislo Any updates on this PR ?

**Pull request closed without merging**
